Story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statusapp.urls', namespace='statusapp')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('story10/', include('story10.urls', namespace='story10')),
]

statusapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'statusapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('status-confirmation/<str:nama>/<str:status>', views.status_confirmation, name='status_confirmation'),
]

story10/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('profile/', views.user_profile, name='profile'),
    path('myprofile/', views.my_profile, name='myprofile'),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8index, name='story8index'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('books', views.list_of_books, name='booklist'),
    re_path(r'^likebook/((?P<bookid>[A-Za-z0-9])|\s)', views.like_book, name='likebook'),
]

statusapp/models.py
from django.db import models

class Status(models.Model):

    def __str__(self):
        return "Status by " + self.nama

    nama = models.CharField(max_length=100)
    status = models.TextField()

story10/models.py
from django.db import models
from django import forms
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractBaseUser
from django.conf import settings
from django.contrib.auth.models import UserManager
from django.contrib.auth import get_user_model

User = get_user_model()

class UserProfile(AbstractBaseUser):

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    REQUIRED_FIELDS = ('user',)
    USERNAME_FIELD = 'username'

    user = models.OneToOneField(User, related_name='myprofile', on_delete=models.CASCADE)

    photo = models.URLField(null=True)
    username = models.CharField(max_length=50, unique=False)
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True)
    website = models.URLField(null=True)

    objects = UserManager()

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

statusapp/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'

story10/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['photo', 'first_name', 'last_name', 'gender', 'website']

statusapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import StatusForm
from .models import Status

def index(request):
    
    form = StatusForm(request.POST or None)
    all_status = Status.objects.all()

    context = {
        'form': form, 
        'all_status': all_status
    }

    if form.is_valid():
        nama = request.POST.get('nama')
        status = request.POST.get('status')
        return redirect('statusapp:status_confirmation', nama, status)


    return render(request, 'statusapp/index.html', context)

def status_confirmation(request, nama, status):

    context = {
        'nama': nama,
        'status': status,
    }

    if request.method == 'POST':
        Status.objects.create(nama=nama, status=status)
        return redirect('statusapp:index')

    return render(request, 'statusapp/status-confirmation.html', context)

story10/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import Http404
from .forms import UserProfileForm
from .models import UserProfile
from django.contrib.auth import get_user_model

User = get_user_model()

def index(request):
    return render(request, 'story10/index.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = form.save(commit=False)
            user.save()
            messages.success(request, f'Welcome {username}, your account is created')
            
            return redirect('story10:index')
    else:
        form = UserCreationForm()
    return render(request, 'register/register.html', {'form':form})

def user_profile(request):
    if request.user.is_authenticated:
        # profile = request.user.UserProfile
        user_instance = UserProfile.objects.filter(user=request.user).first()
        user_profile_form = UserProfileForm(request.POST, request.FILES, instance=user_instance or None)
        if user_profile_form.is_valid():
            profile = user_profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('story10:myprofile')
        return render(request, 'story10/profile.html', {'user_profile_form': user_profile_form})
    raise Http404()

def my_profile(request):
    return render(request, 'story10/myprofile.html')

story8/views.py
from django.shortcuts import render

def story8index(request):
    return render(request, 'story8/index.html')

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from urllib.request import urlopen
import requests
import json

def index(request):
    # if request.is_ajax():
    #     response = requests.get(
    #             "https://www.googleapis.com/books/v1/volumes?q={}".format(
    #                 request.GET["q"]
    #             ))
    #     bookid = response.json()['items']['id']
    #     return render(request, 'story9/index.html', {'book_id': bookid})
    return render(request, 'story9/index.html')

def list_of_books(request):
    if request.is_ajax():
        response = requests.get(
            "https://www.googleapis.com/books/v1/volumes?q={}".format(
                request.GET["q"]
            ))
        return JsonResponse(response.json())
    raise Http404()

def like_book(request, bookid):
    if request.is_ajax():
        return render(request, 'story9/index.html', {'bookid':bookid})
    raise Http404()

statusapp/templates/statusapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link
        href="https://fonts.googleapis.com/css?family=Work+Sans:400,500|Yeseva+One|Caveat|Montserrat|Open+Sans:300|Overpass&display=swap"
        rel="stylesheet">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" id="theme" href="{% static 'statusapp/styles.css' %}">
    {% block styles %}{% endblock %}
</head>

<body>
    <section>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </section>

    <footer>
        <div class="footer">
            <a class="fab fa-instagram" href="https://instagram.com/gpersable" target="_blank"></a>
            <a class="fab fa-twitter" href="https://twitter.com/git_io" target="_blank"></a>
            <a class="fab fa-telegram" href="https://t.me/gpersable" target="_blank"></a>
            <a class="fab fa-github" href="https://github.com/gpersable" target="_blank"></a>

            gita.permatasari91@ui.ac.id
            <a class="gita">&copy; 2020 Gita Permatasari Sujatmiko</a>
        </div>
    </footer>


    <!-- Bootstrap Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    {% block scripts %}{% endblock %}

</body>

</html>

statusapp/templates/statusapp/index.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Status Web App{% endblock %}
{% block content %}

<div class="row justify-content-center">
    <div class="col col-md-4">
        <form class="form-depan" id="statusForm" action="{% url 'statusapp:index' %}" method="POST">
            <h2>Post a Status</h2>
            {% csrf_token %}
            {{ form|crispy }}
            <button id="status_submit" type="submit" class="btn btn-poststatus">Post Status</button>
        </form>
    </div>
    <div class="col col-md-6">

        {% for s in all_status %}
        <ul class="per-status">
            <a class="nama">{{ s.nama }}</a><a style="color: #5a7068;"> posted:</a><br>
            <a class="status">{{ s.status }}</a>
        </ul>
        {% endfor %}

    </div>
</div>




{% endblock %}

statusapp/templates/statusapp/status-confirmation.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Status Confirmation{% endblock %}
{% block content %}

<div class="confirmation">

    <h5 class="the-status"><a class="status-text">{{ status }}</a></h5><br>
    <h4>Apakah benar Anda ingin memasang status tersebut dengan nama pemasang 
        <a style="color: #5a7068">{{ nama }}</a>?</h4>
    <br>

<form id="confirmationForm" action="{% url 'statusapp:status_confirmation' nama status %}" method="POST">
    {% csrf_token %}
    <button id="confirm" class="btn btn-primary" type="submit">Ya, benar</button>
    <a href="{% url 'statusapp:index' %}" id="cancel" name="cancel" class="btn btn-danger">Tidak</a>
</form>

</div>

{% endblock %}

story10/templates/register/register.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Story 10 | Signup{% endblock %}
{% block content %}

<h1>Signup to Gita's Website for Story 10</h1>

<form method="POST" class="form-group">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-likedbooks">Signup</button>
</form>

{% endblock %}

story10/templates/story10/index.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Story 10{% endblock %}
{% block content %}

<section>
    <div class="text-center mt-5">

        <h1>Hello! This is Gita's Website for Story 10.</h1>

        {% if user.is_authenticated %}
        <h3>Selamat datang, {{ user.get_username }}.</h3>
        <a href="{% url 'story10:profile' %}" name="profile" class="btn btn-likedbooks mt-4 mr-2">Edit Profile</a>
        <a href="{% url 'story10:myprofile' %}" name="myprofile" class="btn btn-likedbooks mt-4 mr-2">My Profile</a>
        <a href="{% url 'story10:logout' %}" class="btn btn-danger mt-2">Logout</a>
        {% else %}
        <a href="{% url 'story10:login' %}" name="login" class="btn btn-likedbooks mt-2 mr-2">Login</a>
        <a href="{% url 'story10:register' %}" name="signup" class="btn btn-likedbooks mt-2">Signup</a>
        {% endif %}

    </div>
</section>

{% endblock %}

story10/templates/story10/myprofile.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Story 10 | My Profile{% endblock %}
{% block content %}

<section>
    <div class="text-center mt-5">

        <h1>My Profile</h1>

        {% if user.is_authenticated %}
        <img src="{{ user.myprofile.photo }}" width=150 alt="">
        <br><br>
        
        <!-- <p>{{ user.myprofile.photo }}</p> -->
        <p>Username: {{ user.username }}</p>
        <p>First Name: {{ user.myprofile.first_name }}</p>
        <p>Last Name: {{ user.myprofile.last_name }}</p>
        <p>Gender: {{ user.myprofile.gender }}</p>
        <p>Website: <a href="{{ user.myprofile.website }}">{{ user.myprofile.website }}</a></p>

        
        {% endif %}

    </div>
</section>

{% endblock %}

story10/templates/story10/profile.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Story 10{% endblock %}
{% block content %}

<section>
    <div class="text-center mt-5">

        <h1>Hello! This is Gita's Website for Story 10.</h1>

        {% if user.is_authenticated %}
        <form action="" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ profile }}
            {{ user_profile_form|crispy }}
            <button type="submit" name="update_profile" class="btn btn-likedbooks mt-2">Update Profile</button>
        </form>
        {% endif %}

    </div>
</section>

{% endblock %}

story8/templates/story8/index.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% block title %}Story 8{% endblock %}
{% block content %}


<!-- <div class="section">
    <h3>Section 1
        <a class="up"></a><a class="down"></a>
    </h3>
    <div>
        <p>Isi section 1</p>
    </div>
</div>

<div class="section">
    <h3>Section 2
        <a class="up"></a><a class="down"></a>
    </h3>
    <div>
        <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at
            aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam.
            In suscipit faucibus urna. </p>
    </div>
</div>

<div class="section">
    <h3>Section 3
        <a class="up"></a><a class="down"></a>
    </h3>
    <div>
        <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in
            massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna
            quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui. </p>
        <ul>
            <li>List item one</li>
            <li>List item two</li>
            <li>List item three</li>
        </ul>
    </div>
</div>

<div class="section">
    <h3>Section 4
        <a class="up"></a><a class="down"></a>
    </h3>
    <div>
        <p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
            mauris vel est. </p>
        <p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus. Class aptent taciti sociosqu ad
            litora torquent per conubia nostra, per inceptos himenaeos. </p>
    </div>
</div> -->

<h2 style="text-align: center;">Story 8</h2>

<button class="btn switch" id="switch">Switch Theme</button>

<div class="accordions">
    <div class="section">
        <button class="accordion">Aktivitas Saat Ini</button>

        <div class="up-down">
            <a class="up"></a> <a class="down"></a>
        </div>

        <div class="panel">
            <p>
                <ul>
                    <li>Kuliah online</li>
                    <li>Melakukan hobi</li>
                    <li>#dirumahaja</li>
                </ul>
            </p>
        </div>
    </div>

    <div class="section">
        <button class="accordion">Pengalaman Organisasi</button>

        <div class="up-down">
            <a class="up"></a> <a class="down"></a>
        </div>

        <div class="panel">
            <p>
                <ul>
                    <li>Staf IT Force FUKI Fasilkom UI 2020</li>
                    <li>Staf Bidang Keakhwatan DKM Al-Furqon SMA Negeri 3 Bandung</li>
                    <li>Staf Bidang Pendidikan OSIS SMP Nassa</li>
                </ul>
            </p>
        </div>
    </div>

    <div class="section">
        <button class="accordion">Pengalaman Kepanitiaan</button>

        <div class="up-down">
            <a class="up"></a> <a class="down"></a>
        </div>

        <div class="panel">
            <p>
                <ul>
                    <li>Koordinator Publikasi dan Dokumentasi Akhwat Fest 2017</li>
                    <li>Penanggungjawab Quiz Day SMP Nassa</li>
                    <li>Ketua Pelaksana Acara Hari Kebangkitan Nasional 2014/2015</li>
                </ul>
            </p>
        </div>
    </div>

    <div class="section">
        <button class="accordion">Prestasi</button>

        <div class="up-down">
            <a class="up"></a> <a class="down"></a>
        </div>

        <div class="panel">
            <p>
                <ul>
                    <li>Peraih NEM SMP Terbaik ke-3 se-Kota Bekasi</li>
                    <li>Juara 2 Lomba Sudoku</li>
                </ul>
            </p>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script src="{% static 'story8/scripts.js' %}"></script>

{% endblock %}

story9/templates/story9/index.html
{% extends 'statusapp/base.html' %}
{% load static %}
{% block title %}Books{% endblock %}
{% block content %}

<section>
  <div class="win-sm">
    <h1>Cari Buku:</h1>
  </div>
  <div class="win-sm d-sm-flex mb-4">
    <input type="text" name="q" class="form-control" placeholder="Cari buku...">
    <button class="btn btn-primary" id="search">Cari</button>
  </div>
</section>

<!-- Modal -->
<section>
  <div class="container-fluid">

    <button type="button" class="btn btn-likedbooks" data-toggle="modal" data-target=".bd-example-modal-lg">
      Top Liked Books
    </button>

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
      aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Top Liked Books</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Harusnya ada list 5 buku dengan like terbanyak tapi fitur like-nya belum terimplementasi hehe
          </div>
          <div class="modal-footer">
            &copy; 2020 Gita Sujatmiko
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

<section>
  <center>
    <div class="win-sm">
      <div id="book-header" class="d-none d-md-block font-weight-bold b-light">
        <div class="row mx-0">
          <div class="col-2 p-2">Gambar</div>
          <div class="col-2 p-2">Judul Buku</div>
          <div class="col-2 p-2">Penulis</div>
          <div class="col-2 p-2">Publisher</div>
          <div class="col-2 p-2">Likes</div>
        </div>
      </div>
      <div id="books">
      </div>
    </div>
  </center>

</section>


{% endblock %}

{% block scripts %}

<script>
  var book_url = "{% url 'story9:booklist' %}?q=";
  var csrftoken = "{{ csrf_token }}";
</script>

<script src="{% static 'story9/scripts.js' %}"></script>

{% endblock %}